version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: transactionservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d transactionservice -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=transactionservice
      - APP_PORT=8081
      - KAFKA_BOOTSTRAP_SERVER=