version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=userservice
      - APP_PORT=8082
      - KAFKA_BOOTSTRAP_SERVER=

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
